### ISSUE TITLE
 Spiro curves are  better curves in numerical quality 

### ISSUE THREAD

**Issue by stefano2734** [mlau154/pymead#23]
Bezier are a standard of curves in airfoil.

but they have often some weakness. 
good quality is often not available.

see phd of Dr, Levien: https://levien.com/phd/phd.html

see page 141 for Bézier curve error by arm parameter. 
A small zone of low errors are here seen.

perhaps Spiro curves are the next level for airfoil curves.

**Comment by mlau154** [comment]
Hi @stefano2734,

Can you explain what you mean by "numerical quality" and "good quality?" I agree that Bézier curves have some weaknesses, but they also have many advantages, as pointed out by Dr. Levien in his dissertation. One important advantage is straightforward export to CAD packages, which Spiro curves do not share.

The plot you pointed out (Figure 9.5?) is in the context of converting clothoid curves to Bézier curves, which is not a concern for the applications of pymead. The "small zone of low errors" does not apply to the evaluation or use of Bézier curves in general, but rather to the conversion from clothoid curves to Bézier curves.

I had never heard of Spiro curves, but they are quite intriguing! They do not have a mainstream use in airfoil parametrization, but it would be something interesting to explore. I am open to adding other curve types to pymead, so feel free to submit a pull request with a Spiro curve feature if you are so inclined. I would be happy to walk you through adding these curve types to the GUI if you would like.

-Matt

**Comment by stefano2734** [comment]
In Inkscape is a spiro tool and Dr. Levien made a tool for fonts. 
and raphlinus made on GitHub a spiro tool 
With source from https://levien.com/spiro/
See
https://github.com/raphlinus/spiro
and https://github.com/fontforge/libspiro
can you look about this for a fast link or adaption to your software.
you are here the expert for your software.

I will look in the next months, what I can here do.

**Comment by mlau154** [comment]
To adapt the spiro curve to pymead, you would need to subclass the [ParametricCurve class](https://github.com/mlau154/pymead/blob/master/pymead/core/parametric_curve.py). Really the most important method to implement is the "evaluate" method, which takes a single parameter value or a vector of parameter value and evaluates the curves based on the parameters. See the [Bezier class](https://github.com/mlau154/pymead/blob/master/pymead/core/bezier.py) as an example implementation. There would of course be various different design parameters to control than in the Bezier case, but that should not be to bad to handle. If you wanted to implement the core functionality, I could take it from there and add it to the GUI.

I can't tell from those repos where the actual spiro curve code is written. Perhaps we could get permission from Ralph to adapt just the relevant code from his repos in pymead? I don't mind adding repos as submodules, but these repos seem to not be up to date or have any maintenance. Therefore, I would prefer to just take what we need here.

-Matt

**Comment by stefano2734** [comment]
Thanks for the fast excellent answer. I will look for spiro action in the next month or year. But other user can do faster action, if they want make some spiro lines of code with the existing information of Levien and you.
Libspiro was updated last week to version 1.5.
https://github.com/fontforge/libspiro
